#!/usr/bin/env python3
"""Write the tutorial's pages, docs/tutorial/NN-step.md, from the demo's step
READMEs: the tutorial is the demo, and each step's README is its page.

A README is read where it is written, beside the step's files: in the
repository, and in the data folder where the TUI's start page writes the demo
. There no documentation lies beside it, so a README links to the
documentation by its address on the published site, and to an image by its
address in the repository. A page of the site links within the site, so this
script copies each README and rewrites its links:

- a page of the site, `…/latest/PATH.html`, or an image of docs/ in the
  repository, becomes a link relative to docs/tutorial/;
- `../NN-step/README.md`, the next or the previous step, becomes that step's
  page, and `../README.md` the tutorial's index;
- any other relative link, a file of the step, becomes that file's address on
  the repository, since the site does not hold the demo's files.

    tools/generate-tutorial.py           write the pages
    tools/generate-tutorial.py --check   exit 1 when a page is not what the
                                         README makes (tools/check-docs.py
                                         runs it)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
READMES = ROOT / "fixtures" / "brewing" / "readme"
PAGES = ROOT / "docs" / "tutorial"
SITE = "https://zelyph.github.io/SampleKit/latest"
REPOSITORY = "https://github.com/zelyph/SampleKit"
BRANCH = "main"
RAW = f"https://raw.githubusercontent.com/zelyph/SampleKit/{BRANCH}"
PAGE_ADDRESS = re.compile(re.escape(SITE) + r"/([^)\s#]*)\.html(#[^)\s]*)?")
IMAGE_ADDRESS = re.compile(re.escape(RAW) + r"/docs/([^)\s#]*)")
LINK = re.compile(r"(\]\()([^)\s]+)(\))")
STEP = re.compile(r"\.\./(\d\d-[\w-]+)/README\.md(#[^)\s]*)?$")


def relative_to_tutorial(path):
    """A path under docs/, as a page of docs/tutorial/ links to it."""
    if path.startswith("tutorial/"):
        return path[len("tutorial/"):]
    return "../" + path


def rewrite(target, step):
    found = PAGE_ADDRESS.fullmatch(target)
    if found:
        return relative_to_tutorial(found.group(1) + ".md") + (found.group(2) or "")
    found = IMAGE_ADDRESS.fullmatch(target)
    if found:
        return relative_to_tutorial(found.group(1))
    if re.match(r"[a-z]+://", target) or target.startswith(("#", "mailto:")):
        return target
    found = STEP.fullmatch(target)
    if found:
        return f"{found.group(1)}.md" + (found.group(2) or "")
    if target in ("../README.md", "../"):
        return "index.md"
    return f"{REPOSITORY}/blob/{BRANCH}/examples/brewing/{step}/{target}"


def page(readme):
    step = readme.stem
    text = LINK.sub(lambda m: m.group(1) + rewrite(m.group(2), step) + m.group(3),
                    readme.read_text())
    return (f"<!-- Generated by tools/generate-tutorial.py from "
            f"fixtures/brewing/readme/{readme.name}: edit that file, then run "
            f"the script. -->\n\n{text}")


def pages():
    return {PAGES / readme.name: page(readme)
            for readme in sorted(READMES.glob("[0-9][0-9]-*.md"))}


def main():
    check = "--check" in sys.argv[1:]
    stale = []
    for path, text in pages().items():
        if path.exists() and path.read_text() == text:
            continue
        if check:
            stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        for name in stale:
            print(f"{name} is not what its README makes: run tools/generate-tutorial.py")
        sys.exit(1)


if __name__ == "__main__":
    main()
